// Mocks generated by Mockito 5.4.6 from annotations
// in vence_ai/test/viewmodels/offers_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:geolocator/geolocator.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:vence_ai/models/offer.dart' as _i5;
import 'package:vence_ai/repositories/location_repository.dart' as _i7;
import 'package:vence_ai/repositories/offers_repository.dart' as _i2;
import 'package:vence_ai/utils/result.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OffersRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOffersRepository extends _i1.Mock implements _i2.OffersRepository {
  MockOffersRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Offer>>> fetchOffers() =>
      (super.noSuchMethod(
            Invocation.method(#fetchOffers, []),
            returnValue: _i3.Future<_i4.Result<List<_i5.Offer>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Offer>>>(
                this,
                Invocation.method(#fetchOffers, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Offer>>>);
}

/// A class which mocks [LocationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationRepository extends _i1.Mock
    implements _i7.LocationRepository {
  MockLocationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i8.Position>> determinePosition() =>
      (super.noSuchMethod(
            Invocation.method(#determinePosition, []),
            returnValue: _i3.Future<_i4.Result<_i8.Position>>.value(
              _i6.dummyValue<_i4.Result<_i8.Position>>(
                this,
                Invocation.method(#determinePosition, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.Position>>);
}
